### ISSUE TITLE
Problem with lures

### ISSUE THREAD

**Issue by Goatella** [KevinTyrrell/FishingBot#12]
Hi!  Thanks for this fishing bot.  I am able to get it to work great for fishing but not for lures.

When it tries to apply a lure I see the icon for my fishing pole hover out onto the screen.  Like what would happen if I click on the pole and was in the process of dragging it to an action bar.  The lure is then never applied.

I am playing vanilla, on a Mac.

**Comment by KevinTyrrell** [comment]
Hey Goatella, 

I believe the issue is because my program attempted to type `/use Bright Baubles` but vanilla wow does not support the `/use` command. In order for that to work, you must an addon like Improved Macro or Super Macro to enable the `/use` command. The reason for this is because the game doesn't know where the lure is in your bags, so it needs to search for them. You can find a copy of Improved Macro in my 'Releases' page in the zipped file called `If_on_1_12_1`

**Comment by Goatella** [comment]
Hi!
I had SuperMacro but I'm wondering now if it was a bad version or something, it came bundled with another mod I was using.  In installed Improved Macro from your zip file and it works great.  Thank you!

**Comment by KevinTyrrell** [comment]
@Goatella Thank you for giving me this feedback. I actually am not satisfied with having Improved Macro being required for 1.12.1 and intend to find a way to avoid it. Unfortunately to avoid using that would involve copy-pasting a large amount of Lua code into the chat client instead of just "/use Lure". Anyhow I will fix that at some point. 

Let me know if you run into any other issues. Thank you.
