### ISSUE TITLE
Calibration not working on 4K

### ISSUE THREAD

**Issue by TimerErTim** [KevinTyrrell/FishingBot#27]
I have a 4K Monitor and when I try to calibrate, it always fails. Even if I specify the tooltip area, have the game in focus and do everything as wanted from me, I get an Error message.

You can even see the error message in the screenshot
![Screenshot from me calibrating](https://user-images.githubusercontent.com/27965164/83949049-e655ef00-a821-11ea-9a15-5456b3250662.jpg)

**Comment by TimerErTim** [comment]
I managed to debug your code myself and came to the conclusion, that the error was the selectionArea. The pixels didn't match with the area I selected on my screen. I hardcoded the values for left.x, left.y, etc... and now it works.
That was in your second release. I looked into your master branch as it is now and saw, that you completely changed the calibrate method. I don't know if that fixes the problem, wasn't able to test it out.
Just wanted to let you know.

**Comment by KevinTyrrell** [comment]
Thank you for looking into this. The executable you're running is unfortunately very far out of date, but that's only because I had to stop my next re-write half way through. When I complete the rewrite I will absolutely address this. In fact, the need for calibrating will be gone all-together. Unfortunately until I complete it, the only change I can suggest is changing your resolution to 1920x1080 for the moments in which you use FishingBot.

Hopefully your changes allows the program to work properly outside of that one defect. Keep in mind Blizzard also changed the ways lures are applied, and I have yet to fully patch that. It's a simple one change as well -- instead of `PickupInventoryItem` it would be changed to `/use 14` or something such as that.
